sudo: required

language: scala

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - net-tools

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

services:
  - docker

scala:
  - 2.11.8

env:
  - DOCKER_DIR="../docker/"

script:
  - echo "hello"
#  - sbt ci

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - export JAR="target/scala-2.11/telemetry-streaming-assembly-0.1-SNAPSHOT.jar"
  - git config --local user.name "fbertsch"
  - git config --local user.email "fbertsch@mozilla.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - export AUTO_DEPLOY_REGEX="\[auto-deploy\]"

deploy:
  - provider: releases
    api_key:
      secure: GhKttYjlrlm5mkAaApg563yj60ZoPWZaaTEt9KIqXXIayGVOGQTnyvmSSKAGBlwAj5PGVWMAalAOP3nE8zjv5kCA0EjQLTYvG+FZNJRYzSAtjOuP5GtfkBrOJdd+0D9y2h1iSDZfUNyayo7wHF7GNXEnYtywGrU24Do6NhYm6fx2+bIyXWZJFp+9JwnB3eFIs5mIdSp9IyouLCa/5pMSw0Z60qUjvVsGEGzxxPBjrT7Oa63XuJG1KdzBgR1FIoJOK0x5I6m2jQFl4/TqFrZFqdWRRp0NdFdxdOPG6Hojw0MuQxI9/1h/uMX3Ws2UzmBn3h4oyUMfpuxdTT+DFME61iyHAusQZRegt7x328RcOjyiA2NJ2DDW4WQfjBLIa/wGsyNnL+SVDh9SU1/6/5QJwO/J8r+IIiL0Y6Nb+Ocw9m78LUUUVapGKBWMAQv75y7ZxFJD20HkaqCv3Lb7x6NUcSWUS/0T3Bp/nndgkTNAWT97to+7YHhBEeJr8MLZ3MYVNfrb+HsbSZ3pwfcg45K7JYIdcmyJw/JD/XUz5tT/q7+rdVEfcXfcS2CVaucXTvDZWVmHM2MM+YJ/ttflz3lYS9MAHKm4jHw/5Kr17hjNeTGh2IAe0Hq7YLtTbP/FcGQSS62JccncpbfSgYEZVEaRjuaRAXjKa1U5ktvO27G+Gds=
    on:
      repo: mozilla/telemetry-streaming
      condition: $TRAVIS_COMMIT_MESSAGE =~ $AUTO_DEPLOY_REGEX
      all_branches: true
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      repo: mozilla/telemetry-streaming
      all_branches: true
